### ISSUE TITLE
Facebook "GetFeed" Fields Getting Dropped

### ISSUE THREAD

**Issue by Strainyy** [wso2/esb-connectors#453]
Looks like fields aren't being accepted. So I just end up getting the default "id, message, created_time" fields.

Wire Debug:
```[2015-12-15 19:42:48,258] DEBUG - wire << "GET /409521282507981/feed?limit=10&access_token=[ACCESS_TOKEN]&fields= HTTP/1.1[\r][\n]"```

**Comment by keerthu** [comment]
This is fixed and updated in WSO2 store. Please check with that. 

Please use dev mail list (dev@wso2.org) for your queries so that we can help you quickly.

**Comment by Strainyy** [comment]
@keerthu please update the version numbers or have a "last updated" date in the WSO2 store. It often makes it difficult to debug.
